### PR TITLE
Support Fanv2

### PR DESCRIPTION
**Pull request by p-x9**
Support Fanv2.(developer document is [here](https://developers.homebridge.io/#/service/Fanv2))
I will finally write a readme as well.

### CODE REVIEW

**Comment by p-x9** [comment]
I think that it related to #42

**Comment by benzman81** [comment]
Please also add this to the README.

**Comment by p-x9** [comment]
I wrote README.
Please check it.

**Comment by benzman81** [comment]
@p-x9 shame on me. Didn't see it.

**Comment by benzman81** [comment]
published in 0.1.12

**Comment by p-x9** [comment]
Thanks.
I'm happy if I could contribute in any way.

**Pull request merged**
