### PR TITLE
Add Config UI X - config.schema.json

### PR DESCRIPTION
**Pull request by donavanbecker**
@benzman81 I have added the `config.schema.json` for easier setup of webhooks. This is just the basic. I am working on making it look better over time.

### CODE REVIEW

**Comment by donavanbecker** [comment]
@benzman81, okay it should be good to go! The only thing you may want to add is if statements, for one certain thing should be used.

**Comment by donavanbecker** [comment]
also might be worth it to get your plugin [verified](https://github.com/homebridge/homebridge/wiki/verified-Plugins).

**Comment by donavanbecker** [comment]
config schema json
config schema json_expanded

**Comment by benzman81** [comment]
Could you resolve conflicts, please?

**Comment by donavanbecker** [comment]
> Could you resolve conflicts, please?

done! Changed version to `0.1.2`.

**Comment by benzman81** [comment]
Puh, that would add over 1.200 lines of „code“ for about 2.000 lines of real code. Dont know if that is justified. I habe to sleep over this a few days.

**Comment by donavanbecker** [comment]
> Puh, that would add over 1.200 lines of „code“ for about 2.000 lines of real code. Dont know if that is justified. I habe to sleep over this a few days.

unless you have a better way to incorporate config-ui-x schema? [Config-UI-X](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI) and [config.schema.json](https://developers.homebridge.io/#/config-schema). Let me know if you want me to look into this more?

**Comment by benzman81** [comment]
I think I have an idea. Might take some time, but I will check it.

**Pull request merged**
