### PR TITLE
Added support for temperature, humidity and thermostats

### PR DESCRIPTION
**Pull request by iEns**
Feel free to use my additions if you like.

### CODE REVIEW

**Comment by cis2131** [comment]
This is a great addition.. Would be nice to have a brightness/dimmer function as well, then i think it support most basic functions in homekit...

**Comment by benzman81** [comment]
I created an issue for brightness/dimmer function.

**Comment by benzman81** [comment]
Thx for contribution.

**Comment by benzman81** [comment]
Now available as v.0.0.31 via NPM.

**Pull request merged**
