### PR TITLE
Added body, form and custom headers for switches, pushbuttons, lights, thermostats, garage door openers, window coverings, lock mechanism & security system.

### PR DESCRIPTION
**Pull request by EddyK69**
You can now set body, form and custom headers for switches, pushbuttons, lights, thermostats, garage door openers, window coverings, lock mechanism & security system.

For example: use 'on_form' instead of 'on_body' to use for x-www-form-urlencoded JSON.

### CODE REVIEW

**Comment by EddyK69** [comment]
> Great addition. Will look into it on the weekend.

Did you have time to look at it? ;)

**Comment by benzman81** [comment]
sorry for the delay, actually forgot about it :-D plugin seems to run fine and code looks good. So i merged it, but didn't test the new functionality.

**Comment by EddyK69** [comment]
> sorry for the delay, actually forgot about it :-D plugin seems to run fine and code looks good. So i merged it, but didn't test the new functionality.

Thank you!

**Comment by EddyK69** [comment]
Homebridge still reports the old version  0.0.49. How can i update to the latest version 0.0.50?

**Comment by benzman81** [comment]
@EddyK69 sorry, forgot to publish on npm. Now, v0.0.50 should be available.

**Pull request merged**
