### PR TITLE
Added Window Coverings accessory

### PR DESCRIPTION
**Pull request by kaowiec**
Added Window Coverings Accessory and updated readme.md
It works for me since few days.
To moove covers You haave to set links for open, close and 20, 40, 60, 80% 
Homekit "need to see" current position and target position. Position state is not tested and is not mandatory. 

Regards

### CODE REVIEW

**Comment by benzman81** [comment]
@kaowiec would be great if you resolve the conflicts first ;-)

**Comment by kaowiec** [comment]
Forgive my ignorance of github procedures ... I am new here.
Did I resolve conflicts?
If not ... I will read the manual ...

**Comment by benzman81** [comment]
Conflicts resolved ;-) I will look into it within the next days and merge it.

**Comment by benzman81** [comment]
Merged, thanks for contribution.

**Pull request merged**
